sudo: required          # Super user level permissions required

services:
    - docker            # We need Docker CLI pre-installed (Travis will install a copy of Docker)

before_install:         # Steps before we deploy or run our tests
    - docker build -t my-docker-react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true my-docker-react-app npm run test

# Telling Travis how to take our application and deploy to AWS
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-205405356006"
    bucket_path: "docker-react"
    # Only attempt to deploy when new changes are pushed to master branch (not feature branch)
    on:
        branch: master
    # Access Keys, we've added to Travis CI's environment variables. Get it from there
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY