sudo: required          # Super user level permissions required

services:
    - docker            # We need Docker CLI pre-installed (Travis will install a copy of Docker)

before_install:         # Steps before we deploy or run our tests
    - docker build -t my-docker-react-app -f Dockerfile.dev .

script:
    - docker run -it my-docker-react-app npm run test -- --coverage